function buildHTMLdoc
%BUILDHTMLDOC Builds html documentation from comments in files
% Before running this script the contents.m file must be generated by hand
% (until we find how to do it programmatically)
docFolder = '..\Documentation';
mkdir('..\Documentation');

contentsFile = 'Package\Contents.m';
nBuildHTMLdoc(contentsFile, docFolder, false);
contentsFile = 'Package\+ing\Contents.m';
nBuildHTMLdoc(contentsFile, docFolder, true)

function nBuildHTMLdoc( contentsFile , docFolder , isPackage )


%% Open Content file and read top level class name
fid = fopen(contentsFile,'r');
if isPackage
    TopLevel = textscan(fid, '%*c %*1s %s',1);
    prefix = [];
else
    TopLevel = textscan(fid, '%*1s %s',1);
    prefix = ['Code',filesep];
end
fclose(fid);

%% Generate HTML for top level
% remove links that require MATLAB and substitute them with html links
fid = fopen([docFolder,filesep,TopLevel{1,1}{1,1} '.html'],'w');
html = help2html([prefix,TopLevel{1,1}{1,1}],[],'-doc');
str = 'matlab:doc';
sub = '.html';
N = length(strfind(html, str));
for i = 1:N
    k = strfind(html, str);
    html = [html(1:k(1)-1) html(k(1)+11:end)];
    tmp = html(k(1):end);
    c = strfind(tmp, '"');
    html = [html(1:k(1)+c(1)-2) sub html(k(1)+c(1)-1:end)];
end
fprintf(fid,'%s', html);
fclose(fid);

%% Read all Contents
fid = fopen(contentsFile,'r');
txt = textscan(fid,'%*c %s %*[^\n]','HeaderLines',3);
fclose(fid);

%% Generate HTML for all Contents
% remove links that require MATLAB and substitute them with html links
% remove links that are dead
for i = 1:length(txt{1,1})
    if isPackage
        fid  = fopen([docFolder,filesep,TopLevel{1,1}{1,1} '.' txt{1,1}{i,1} '.html'],'w');
    else
        fid  = fopen([docFolder,filesep,txt{1,1}{i,1} '.html'],'w');
    end
    html = help2html([TopLevel{1,1}{1,1} '.' txt{1,1}{i,1}],[],'-doc');
    str1 = 'matlab:helpwin';
    str2 = 'matlab:doc';
    sub  = '.html';
    N1 = length(strfind(html, str1));
    N2 = length(strfind(html, str2));
    for i = 1:N1
        k = strfind(html, str1);
        tmp = html(k(1):end);
        c = strfind(tmp, '>');
        html = [html(1:k(1)-10) html(k(1)+c(1):end)];
    end
    for i = 1:N2
        k = strfind(html, str2);
        html = [html(1:k(1)-1) html(k(1)+11:end)];
        tmp = html(k(1):end);
        c = strfind(tmp, '"');
        html = [html(1:k(1)+c(1)-2) sub html(k(1)+c(1)-1:end)];
    end
    fprintf(fid,'%s', html);
    fclose(fid);
end

