function test_suite = Test_CR289EmptyParametersException()

    disp('Initialising Test_CR289EmptyParametersException')
 
    initTestSuite; 


end

function TestEmptyParametersException()

    fprintf('\nStarting test for empty parameters in validation result...')
    
    diary tempFileName.txt;
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationEmptyParameters.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    outputPath = RSGBootstrapValidate(bootstrapValidationControlFilePath);
    toc
    
    diary off;
    
    searchTerm = 'ValidationResults:AddResults:EmptyType';
    searchTerm2 = 'ValidationResults:AddResults:EmptyIdentifier';
    searchTerm3 = 'ValidationResults:AddResults:EmptyValue';
    
    noException = SearchFileForString('tempFileName.txt', searchTerm);
    noException2 = SearchFileForString('tempFileName.txt', searchTerm2);
    noException3 = SearchFileForString('tempFileName.txt', searchTerm3);
 
    delete tempFileName.txt;

    assertFalse(~noException && ~noException2 && ~noException3, 'No exception has been thrown when empty parameters are encountered in validation result');
    
    files = areThereFilesInTheDirectory(outputPath);
    
    assertTrue(isempty(files), 'Some files have been generated by the boostrap validation process when they shouldn''t');
    
    fprintf('Finishing test for empty parameters in validation result...\n');

end