function test_suite = Test_CR289DuplicateDataSetNameException()

    disp('Initialising Test_CR289DuplicateDataSetNameException')
 
    initTestSuite; 


end

function TestDuplicateDataSetNameException()

    fprintf('\nStarting test for duplicate data set name in control XML file...')
    
    diary tempFileName.txt;
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationDuplicateDataSetName.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    outputPath = RSGBootstrapValidate(bootstrapValidationControlFilePath);
    toc
    
    diary off;
    
    searchTerm = 'BootstrapValidationEngine:ProcessValidationReport:DuplicateDataSeriesName';
    
    noException = SearchFileForString('tempFileName.txt', searchTerm);
 
    delete tempFileName.txt;

    assertFalse(noException, 'No exception has been thrown when a duplicate data set name has been provided in the control XML file');
    
    files = areThereFilesInTheDirectory(outputPath);
    
    assertTrue(isempty(files), 'Some files have been generated by the boostrap validation process when they shouldn''t');
    
    fprintf('Finishing test for duplicate data set name in control XML file...\n');

end