function test_suite = Test_CR289InvalidAlgorithmPropertyException()

    disp('Initialising Test_CR289InvalidAlgorithmPropertyException')
 
    initTestSuite; 


end

function TestInvalidAlgorithmPropertyException()

    fprintf('\nStarting test for invalid bootstraping algorithm property...')
    
    diary tempFileName.txt;
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationInvalidAlgorithmProperty.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    outputPath = RSGBootstrapValidate(bootstrapValidationControlFilePath);
    toc
    
    diary off;
    
    searchTerm = 'BootstrapValidationEngine:SetAlgorithmParams:InvalidProperty';
    
    noException = SearchFileForString('tempFileName.txt', searchTerm);
 
    delete tempFileName.txt;

    assertFalse(noException, 'No exception has been thrown when an invalid property for the bootstraping validation algorithm has been provided');
    
    files = areThereFilesInTheDirectory(outputPath);
    
    assertTrue(isempty(files), 'Some files have been generated by the boostrap validation process when they shouldn''t');
    
    fprintf('Finishing test for invalid bootstraping algorithm property...\n');

end