function test_suite = Test_CR289EmptyDataSeriesException()

    disp('Initialising Test_CR289EmptyDataSeriesException')
 
    initTestSuite;


end

function TestEmptyDataSeriesException()

    fprintf('\nStarting test for empty data series...')
    
    diary tempFileName.txt;
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationInvalidDataSeries.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    outputPath = RSGBootstrapValidate(bootstrapValidationControlFilePath);
    toc
    
    diary off;
    
    searchTerm = 'Data for the Data Series';
    searchTerm2 = 'cannot be found';
    
    noException = SearchFileForString('tempFileName.txt', searchTerm);
    noException2 = SearchFileForString('tempFileName.txt', searchTerm2);
 
    delete tempFileName.txt;

    assertFalse(noException && noException2, 'No exception has been thrown when empty data series were found');
    
    files = areThereFilesInTheDirectory(outputPath);
    
    assertTrue(isempty(files), 'Some files have been generated by the boostrap validation process when they shouldn''t');
    
    fprintf('Finishing test for empty data series...\n');

end