function test_suite = Test_CR289ToExceedingEffectiveException()

    disp('Initialising Test_CR289ToExceedingEffectiveException')
 
    initTestSuite; 


end

function TestToExceedingEffectiveException()

    fprintf('\nStarting test for to date exceeding effective date...')
    
    diary tempFileName.txt;
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationToExceedingEffective.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    outputPath = RSGBootstrapValidate(bootstrapValidationControlFilePath);
    toc
    
    diary off;
    
    searchTerm = 'BootstrapValidationEngine:PerformParameterValidation:ToDateExceedingEffectiveDate';
    
    noException = SearchFileForString('tempFileName.txt', searchTerm);
 
    delete tempFileName.txt;

    assertFalse(noException, 'No exception has been thrown when the to date exceeds the effective date');
    
    files = areThereFilesInTheDirectory(outputPath);
    
    assertTrue(isempty(files), 'Some files have been generated by the boostrap validation process when they shouldn''t');
    
    fprintf('Finishing test for to date exceeding effective date...\n');

end