function test_suite = Test_CR289WrongValueForTypeStringException()

    disp('Initialising Test_CR289WrongValueForTypeStringException')
 
    initTestSuite; 


end

function TestWrongValueForTypeStringException()

    fprintf('\nStarting test for wrong value provided for type string...')
    
    diary tempFileName.txt;
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationWrongValueForTypeString.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    outputPath = RSGBootstrapValidate(bootstrapValidationControlFilePath);
    toc
    
    diary off;
    
    searchTerm = 'ValidationResults:validateInputParameters:InvalidValueForString';
    
    noException = SearchFileForString('tempFileName.txt', searchTerm);
 
    delete tempFileName.txt;

    assertFalse(noException, 'No exception has been thrown when the wrong value has been provided for type string');
    
    files = areThereFilesInTheDirectory(outputPath);
    
    assertTrue(isempty(files), 'Some files have been generated by the boostrap validation process when they shouldn''t');
    
    fprintf('Finishing test for wrong value provided for type string...\n');

end