function test_suite = Test_CR289OutputInCorrectFolder()

    disp('Initialising Test_CR289OutputInCorrectFolder')
    initTestSuite; 

end

function TestOutputInCorrectFolder()

    fprintf('\nStarting test for output being generated in the correct folder...')
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationOutputInCorrectFolder.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    bootstrapValidationEngine = prursg.BootstrapValidation.BootstrapValidationEngine();
    fprintf('Bootstrap Validation engine has been initialized successfully... \n'); 
    
    fprintf('Calling the BootstrapValidate method... \n'); 
    % Call the BootstrapValidate function
    OutputFilesPath = bootstrapValidationEngine.BootstrapValidate(bootstrapValidationControlFilePath); 
    toc
    disp('Bootstrap validation complete');    
   
    listing = dir(OutputFilesPath);
    
    [dx,dx]=sort([listing.datenum]);
    
    folderName = listing(dx(end)).name;
    
    listingFolder = dir(fullfile(OutputFilesPath, folderName));
    isDir = [listingFolder.isdir];
    
    files = {listingFolder(~isDir).name};
    
    assertTrue(~isempty(files), 'No files have been generated by the boostrap validation process');
    
    files(2,:) = {', '};
    files{2,end} = '';
    
    disp(['The following files have been found in the output directory: ' [files{:}] ]);
    
    fprintf('Finishing test for output being generated in the correct folder...\n');

end