function test_suite = Test_CR289DuplicateIdentifierException()

    disp('Initialising Test_CR289InvalidTypeException')
 
    initTestSuite; 


end

function TestInvalidTypeException()

    fprintf('\nStarting test for duplicate identifier of validation result...')
    
    diary tempFileName.txt;
   
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    
    controlFile = 'bootstrapValidationDuplicateIdentifier.xml';

    % Set file paths
    bootstrapValidationControlFilePath = strcat(pathstr, filesep,'BootstrapControl', filesep, controlFile);
   
    % Start the bootstrap
    disp('Starting the bootstrap validation process');
    tic
    outputPath = RSGBootstrapValidate(bootstrapValidationControlFilePath);
    toc
    
    diary off;
    
    searchTerm = 'ValidationResults:AddResults:DuplicateIdentifier';
    searchTerm2 = 'ValidationResults:AddCustomProperty:DuplicateIdentifier';
    
    noException = SearchFileForString('tempFileName.txt', searchTerm);
    noException2 = SearchFileForString('tempFileName.txt', searchTerm2);
 
    delete tempFileName.txt;

    assertFalse(noException && noException2, 'No exception has been thrown when a duplicate identifier of validation result has been provided');
    
    files = areThereFilesInTheDirectory(outputPath);
    
    assertTrue(isempty(files), 'Some files have been generated by the boostrap validation process when they shouldn''t');
    
    fprintf('Finishing test for duplicate identifier of validation result...\n');

end