deployFolder = 'extract_index_curve';
mkdir(deployFolder)
mkdir([deployFolder,filesep,'distrib'])
mkdir([deployFolder,filesep,'src'])
mcc -o extract_index_curve -W main:extract_index_curve -T link:exe ...
    -d extract_index_curve/distrib ...
    -N -w enable:specified_file_mismatch -w enable:repeated_file ...
    -w enable:switch_ignored -w enable:missing_lib_sentinel ...
    -w enable:demo_license ...
    -v extract_index_curve.m
