deployFolder = 'cat_cashflows';
mkdir(deployFolder)
mkdir([deployFolder,filesep,'distrib'])
mkdir([deployFolder,filesep,'src'])
mcc -o cat_cashflows -W main:cat_cashflows -T link:exe ...
    -d cat_cashflows/distrib ...
    -N -w enable:specified_file_mismatch -w enable:repeated_file ...
    -w enable:switch_ignored -w enable:missing_lib_sentinel ...
    -w enable:demo_license ...
    -v extract_index_curve.m
