addpath Tests
diary on
runAll
diary off
deployFolder = 'miniECAPSCL';
mkdir(deployFolder)
mkdir([deployFolder,filesep,'distrib'])
mkdir([deployFolder,filesep,'src'])
mcc -o miniECAPSCL -W main:miniECAPSCL -T link:exe ...
    -d miniECAPSCL/distrib ...
    -N -p optim -w enable:specified_file_mismatch -w enable:repeated_file ...
    -w enable:switch_ignored -w enable:missing_lib_sentinel ...
    -w enable:demo_license ...
    -v miniECAPSCL.m
